<?xml version="1.0" ?>

<project name="hafen" default="deftgt" xmlns:if="ant:if">
  <property file="build.properties" />
  <property name="ext-lib-base" value="http://www.havenandhearth.com/java" />
  <property name="junit-platform.version" value="1.14.2" />
  <property name="junit-platform.jar" location="lib/ext/junit/junit-platform-console-standalone-${junit-platform.version}.jar" />
  <property name="junit-platform.sha256" value="5566ffe2aa48263867bca745925f73bf7b01591b30d9a60f191c0b16fa0955e9" />
  <!-- Vulkan renderer: LWJGL modules matching the bundled lwjgl-fat (3.4.1), from Maven Central. -->
  <property name="lwjgl-vk.version" value="3.4.1" />
  <property name="lwjgl-vk.jars" value="lwjgl-vulkan-${lwjgl-vk.version}.jar lwjgl-shaderc-${lwjgl-vk.version}.jar lwjgl-shaderc-${lwjgl-vk.version}-natives-windows.jar lwjgl-shaderc-${lwjgl-vk.version}-natives-linux.jar lwjgl-vma-${lwjgl-vk.version}.jar lwjgl-vma-${lwjgl-vk.version}-natives-windows.jar lwjgl-vma-${lwjgl-vk.version}-natives-linux.jar" />

  <path id="client.classpath">
	<pathelement path="lib/ext/jogl/jogl-all.jar" />
	<pathelement path="lib/ext/jogl/gluegen-rt.jar" />
	<pathelement path="lib/ext/lwjgl/lwjgl-fat.jar" />
	<pathelement path="lib/ext/lwjgl/lwjgl-awt.jar" />
	<pathelement path="lib/ext/lwjgl/lwjgl-opengl-fat.jar" />
	<pathelement path="lib/ext/lwjgl-vk/lwjgl-vulkan-${lwjgl-vk.version}.jar" />
	<pathelement path="lib/ext/lwjgl-vk/lwjgl-shaderc-${lwjgl-vk.version}.jar" />
	<pathelement path="lib/ext/lwjgl-vk/lwjgl-vma-${lwjgl-vk.version}.jar" />
	<pathelement path="lib/ext/steamworks/steamworks4j.jar" />
    <pathelement path="etc/json-java.jar" />
    <pathelement path="etc/postgresql-42.7.5.jar" />
    <pathelement path="etc/sqlite-jdbc-3.49.1.0.jar" />
	<pathelement path="lib/jglob.jar" />
  </path>

  <target name="build-env">
    <mkdir dir="build" />
    <mkdir dir="build/classes" />
    <available property="has-res-jar" file="bin/builtin-res.jar" />
    <available property="unpacked-lib" file="build/classes-lib" />
    <condition property="has-panama">
      <javaversion atleast="22" />
    </condition>
  </target>

  <target name="make-buildinfo" depends="build-env">
    <touch file="build/classes/buildinfo" datetime="01/01/2000 12:00 am" />
    <loadproperties srcFile="build/classes/buildinfo" prefix="buildinfo." />
    <exec executable="git" outputproperty="git-rev" failifexecutionfails="false">
      <arg line="rev-parse HEAD" />
    </exec>
    <condition property="buildinfo-unchanged">
      <equals arg1="${buildinfo.git-rev}" arg2="${git-rev}" />
    </condition>
  </target>

  <target name="buildinfo" depends="make-buildinfo" unless="buildinfo-unchanged">
    <echo message="Updating buildinfo" />
    <echo file="build/classes/buildinfo" xml:space="default">
      git-rev = ${git-rev}
    </echo>
  </target>


  <macrodef name="extlib">
    <attribute name="name" />
    <attribute name="path" />
    <attribute name="url" />
    <sequential>
      <local name="@{name}-files" />
      <mkdir dir="@{path}" />
      <loadresource property="@{name}-files">
	<url url="@{url}/lib-files" />
	<filterchain>
	  <prefixlines prefix="@{url}/" />
	</filterchain>
      </loadresource>
      <get dest="@{path}/" usetimestamp="true" maxtime="60" retries="3" verbose="true">
	<resourcelist>
	  <propertyresource name="@{name}-files" />
	</resourcelist>
      </get>
      <touch file="@{path}/has-@{name}" />
    </sequential>
  </macrodef>

  <target name="extlib-env">
    <mkdir dir="lib/ext" />
    <available property="extlib/has-jogl" file="lib/ext/jogl/has-jogl" />
    <available property="extlib/has-lwjgl-base" file="lib/ext/lwjgl/has-lwjgl-base" />
    <available property="extlib/has-lwjgl-gl" file="lib/ext/lwjgl/has-lwjgl-gl" />
    <available property="extlib/has-steamworks" file="lib/ext/steamworks/has-steamworks" />
    <available property="extlib/has-lwjgl-vk" file="lib/ext/lwjgl-vk/has-lwjgl-vk" />
  </target>

  <target name="extlib/jogl" depends="extlib-env" unless="extlib/has-jogl">
    <extlib name="jogl" path="lib/ext/jogl" url="${ext-lib-base}/jogl/current" />
  </target>

  <target name="extlib/lwjgl-base" depends="extlib-env" unless="extlib/has-lwjgl-base">
    <extlib name="lwjgl-base" path="lib/ext/lwjgl" url="${ext-lib-base}/lwjgl/current/lwjgl" />
  </target>

  <target name="extlib/lwjgl-gl" depends="extlib-env, extlib/lwjgl-base" unless="extlib/has-lwjgl-gl">
    <extlib name="lwjgl-gl" path="lib/ext/lwjgl" url="${ext-lib-base}/lwjgl/current/lwjgl-opengl" />
  </target>

  <target name="extlib/lwjgl-vk" depends="extlib-env" unless="extlib/has-lwjgl-vk">
    <property name="lwjgl-vk.url" value="https://repo1.maven.org/maven2/org/lwjgl" />
    <mkdir dir="lib/ext/lwjgl-vk" />
    <get dest="lib/ext/lwjgl-vk/" skipexisting="true" maxtime="120" retries="3">
      <url url="${lwjgl-vk.url}/lwjgl-vulkan/${lwjgl-vk.version}/lwjgl-vulkan-${lwjgl-vk.version}.jar" />
      <url url="${lwjgl-vk.url}/lwjgl-shaderc/${lwjgl-vk.version}/lwjgl-shaderc-${lwjgl-vk.version}.jar" />
      <url url="${lwjgl-vk.url}/lwjgl-shaderc/${lwjgl-vk.version}/lwjgl-shaderc-${lwjgl-vk.version}-natives-windows.jar" />
      <url url="${lwjgl-vk.url}/lwjgl-shaderc/${lwjgl-vk.version}/lwjgl-shaderc-${lwjgl-vk.version}-natives-linux.jar" />
      <url url="${lwjgl-vk.url}/lwjgl-vma/${lwjgl-vk.version}/lwjgl-vma-${lwjgl-vk.version}.jar" />
      <url url="${lwjgl-vk.url}/lwjgl-vma/${lwjgl-vk.version}/lwjgl-vma-${lwjgl-vk.version}-natives-windows.jar" />
      <url url="${lwjgl-vk.url}/lwjgl-vma/${lwjgl-vk.version}/lwjgl-vma-${lwjgl-vk.version}-natives-linux.jar" />
    </get>
    <checksum file="lib/ext/lwjgl-vk/lwjgl-vulkan-${lwjgl-vk.version}.jar" algorithm="SHA-256" property="7f39be7c1e7b14b47d18ec5e23dd25240d2e41c090393524615d760203bf14a6" verifyproperty="lwjgl-vk.ok.1" />
    <checksum file="lib/ext/lwjgl-vk/lwjgl-shaderc-${lwjgl-vk.version}.jar" algorithm="SHA-256" property="72293c0d58aa07205f67233efed3769111e8312c73bd8e1f4c13a44ab255f27f" verifyproperty="lwjgl-vk.ok.2" />
    <checksum file="lib/ext/lwjgl-vk/lwjgl-shaderc-${lwjgl-vk.version}-natives-windows.jar" algorithm="SHA-256" property="d1449f6e4969797230545ec77c2f7478862379e586b35530c3d3651c926cc9ca" verifyproperty="lwjgl-vk.ok.3" />
    <checksum file="lib/ext/lwjgl-vk/lwjgl-shaderc-${lwjgl-vk.version}-natives-linux.jar" algorithm="SHA-256" property="207a09044daa8bb6fed7ff8057411b22d8cc86f3e86939b03428b573e621e21c" verifyproperty="lwjgl-vk.ok.4" />
    <checksum file="lib/ext/lwjgl-vk/lwjgl-vma-${lwjgl-vk.version}.jar" algorithm="SHA-256" property="d6a9677b5d487c97b874c18cb9c726197e9a8773f6a1c031ea9f5950b8c0b3c2" verifyproperty="lwjgl-vk.ok.5" />
    <checksum file="lib/ext/lwjgl-vk/lwjgl-vma-${lwjgl-vk.version}-natives-windows.jar" algorithm="SHA-256" property="b79a4f0679fa5902fafb345792314e400dfdcf04b4c15df700363c448c27ba15" verifyproperty="lwjgl-vk.ok.6" />
    <checksum file="lib/ext/lwjgl-vk/lwjgl-vma-${lwjgl-vk.version}-natives-linux.jar" algorithm="SHA-256" property="4f83a80bc03ad749aa4c9ad7d39d136753e7e862624e7e0ee4ab7b914848815f" verifyproperty="lwjgl-vk.ok.7" />
    <fail message="LWJGL Vulkan jars failed their checksums; delete lib/ext/lwjgl-vk and retry">
      <condition>
        <not>
          <and>
            <istrue value="${lwjgl-vk.ok.1}" />
            <istrue value="${lwjgl-vk.ok.2}" />
            <istrue value="${lwjgl-vk.ok.3}" />
            <istrue value="${lwjgl-vk.ok.4}" />
            <istrue value="${lwjgl-vk.ok.5}" />
            <istrue value="${lwjgl-vk.ok.6}" />
            <istrue value="${lwjgl-vk.ok.7}" />
          </and>
        </not>
      </condition>
    </fail>
    <touch file="lib/ext/lwjgl-vk/has-lwjgl-vk" />
  </target>

  <target name="extlib/steamworks" depends="extlib-env" unless="extlib/has-steamworks">
    <extlib name="steamworks" path="lib/ext/steamworks" url="${ext-lib-base}/steamworks/current" />
  </target>

    <target name="extlib/jogl-arm" depends="extlib/jogl">
        <mkdir dir="lib/ext/jogl" />
        <!-- skipexisting: the URLs are version-pinned, so a file already
             present is already the right one. Without this, every build hits
             jogamp.org and dies on a transient network failure. -->
        <get dest="lib/ext/jogl/" verbose="true" skipexisting="true">
            <url url="https://jogamp.org/deployment/v2.5.0/jar/jogl-all.jar" />
            <url url="https://jogamp.org/deployment/v2.5.0/jar/jogl-all-natives-macosx-universal.jar" />
            <url url="https://jogamp.org/deployment/v2.5.0/jar/gluegen-rt.jar" />
            <url url="https://jogamp.org/deployment/v2.5.0/jar/gluegen-rt-natives-macosx-universal.jar" />
        </get>
        <mkdir dir="lib/ext/jogl/natives/macosx-universal" />
        <unjar src="lib/ext/jogl/jogl-all-natives-macosx-universal.jar" dest="lib/ext/jogl">
            <patternset includes="natives/**" />
        </unjar>
        <unjar src="lib/ext/jogl/gluegen-rt-natives-macosx-universal.jar" dest="lib/ext/jogl">
            <patternset includes="natives/**" />
        </unjar>
    </target>

  <target name="hafen-client" depends="build-env, extlib/jogl, extlib/lwjgl-gl, extlib/lwjgl-vk, extlib/steamworks, resources">
    <condition property="explicit-annotations">
      <javaversion atleast="21" />
    </condition>
    <javac srcdir="src" destdir="build/classes" debug="on"
	   source="1.8" target="1.8" includeantruntime="no"
           encoding="UTF-8"
	   bootclasspath="${boot-classpath}">
      <classpath refid="client.classpath" />
      <compilerarg if:set="explicit-annotations" value="-proc:full" />
      <compilerarg value="-Xlint:unchecked" />
      <compilerarg value="-Xlint:deprecation" />
      <compilerarg value="-Xlint:-options" />
      <!-- <compilerarg value="-Xbarda" /> -->
    </javac>
    <copy todir="build/classes">
      <fileset dir="src" excludes="**/*.java" />
    </copy>
    <copy todir="build/classes/haven" file="etc/ressrv.crt" />
    <copy todir="build/classes/haven" file="etc/authsrv.crt" />
    <copy todir="build/classes/haven" file="etc/res-preload" />
    <copy todir="build/classes/haven" file="etc/res-bgload" />
    <copy todir="build/classes/haven" file="etc/icon.png" />
    <copy file="local-boot.properties" tofile="build/classes/haven/boot-props" failonerror="false" quiet="true" />
  </target>

  <target name="opt/panama" if="has-panama" depends="build-env, hafen-client">
    <mkdir dir="build/opt/panama" />
    <javac srcdir="opt/panama" destdir="build/opt/panama" release="22"
	   debug="on" includeantruntime="no">
      <classpath>
	<pathelement path="build/classes" />
	<pathelement path="lib/jglob.jar" />
      </classpath>
      <compilerarg value="-proc:full" />
      <compilerarg value="-Xlint:unchecked" />
      <compilerarg value="-Xlint:deprecation" />
    </javac>
    <jar destfile="build/hafen-panama.jar" update="true">
      <fileset dir="build/opt/panama" />
    </jar>
  </target>

  <target name="lib-classes" depends="build-env" unless="unpacked-lib">
    <mkdir dir="build/classes-lib" />
    <unjar src="lib/jglob.jar" dest="build/classes-lib">
      <patternset excludes="META-INF/**" />
    </unjar>
  </target>

  <target name="jar" depends="hafen-client, buildinfo, lib-classes">
    <jar destfile="build/hafen.jar" update="true">
      <fileset dir="build/classes" />
      <fileset dir="build/classes-lib" />
      <manifest>
	<attribute name="Main-Class" value="haven.MainFrame" />
	<attribute name="Class-Path" value="hafen-panama.jar jogl-all.jar gluegen-rt.jar lwjgl-fat.jar lwjgl-awt.jar lwjgl-opengl-fat.jar ${lwjgl-vk.jars} steamworks4j.jar builtin-res.jar hafen-res.jar nurgling-res.jar json-java.jar postgresql-42.7.5.jar sqlite-jdbc-3.49.1.0.jar" />
	<attribute name="Add-Exports" value="java.base/java.lang java.desktop/sun.awt java.desktop/sun.java2d" />
	<attribute name="Enable-Native-Access" value="ALL-UNNAMED" />
      </manifest>
    </jar>
    <chmod file="build/hafen.jar" perm="a+x" />
  </target>

  <target name="res-jar" depends="build-env" unless="has-res-jar">
    <get src="${ext-lib-base}/builtin-res.jar" dest="lib/ext/builtin-res.jar"
	 usetimestamp="true" />
    <get src="${ext-lib-base}/hafen-res.jar" dest="lib/ext/hafen-res.jar"
	 usetimestamp="true" />
    <available property="lib-res-jar" file="lib/ext/hafen-res.jar" />
    <fail unless="lib-res-jar" message="hafen-res.jar not available" />
    <available property="lib-builtin-jar" file="lib/ext/builtin-res.jar" />
    <fail unless="lib-builtin-jar" message="builtin-res.jar not available" />
  </target>

  <target name="jars" depends="build-env, jar, extlib/jogl, extlib/lwjgl-gl, extlib/steamworks">
    <copy todir="build" failonerror="false" quiet="true">
      <fileset dir="lib">
	<include name="builtin-res.jar" />
	<include name="hafen-res.jar" />
      </fileset>
    </copy>
    <copy todir="build">
      <fileset dir="lib/ext/jogl"><include name="*.jar" /></fileset>
      <fileset dir="lib/ext/lwjgl"><include name="*.jar" /></fileset>
      <fileset dir="lib/ext/lwjgl-vk"><include name="*.jar" /></fileset>
    </copy>
    <copy file="local-config.properties" tofile="build/haven-config.properties" failonerror="false" quiet="true" />
  </target>

  <target name="bin" depends="jar, extlib/jogl-arm, extlib/lwjgl-gl, extlib/steamworks, res-jar">
    <mkdir dir="bin" />
    <copy todir="bin">
      <fileset dir="build">
	<include name="hafen.jar" />
      </fileset>
      <fileset dir="lib/ext">
	<include name="hafen-res.jar" />
	<include name="builtin-res.jar" />
      </fileset>
      <fileset dir="lib/ext/jogl"><include name="*.jar" /></fileset>
      <fileset dir="lib/ext/lwjgl"><include name="*.jar" /></fileset>
      <fileset dir="lib/ext/lwjgl-vk"><include name="*.jar" /></fileset>
      <fileset dir="lib/ext/steamworks"><include name="*.jar" /></fileset>
    </copy>
    <copy todir="bin" failonerror="false" quiet="true">
      <fileset dir="build">
	<include name="hafen-panama.jar" />
      </fileset>
    </copy>
    <copy file="etc/ansgar-config.properties" tofile="bin/haven-config.properties" />
    <chmod file="bin/hafen.jar" perm="a+x" />
  </target>

  <target name="deftgt" depends="jars, opt/panama, bin" />

  <target name="run" depends="bin">
    <condition property="jogl-exports">
      <javaversion atleast="16" />
    </condition>
    <condition property="jogl-access">
      <javaversion atleast="24" />
    </condition>
    <java jar="bin/hafen.jar" fork="true">
      <sysproperty key="sun.java2d.uiScale.enabled" value="false" />
      <sysproperty key="java.net.preferIPv6Addresses" value="system" />
      <jvmarg if:set="jogl-exports" value="--add-exports=java.base/java.lang=ALL-UNNAMED" />
      <jvmarg if:set="jogl-exports" value="--add-exports=java.desktop/sun.awt=ALL-UNNAMED" />
      <jvmarg if:set="jogl-exports" value="--add-exports=java.desktop/sun.java2d=ALL-UNNAMED" />
      <jvmarg if:set="jogl-access" value="--enable-native-access=ALL-UNNAMED" />
      <!-- <sysproperty key="haven.renderer" value="lwjgl" /> -->
    </java>
  </target>

  <target name="test-env">
    <mkdir dir="lib/ext/junit" />
    <available property="test/junit-present" file="${junit-platform.jar}" />
  </target>

  <target name="test-verify" depends="test-env" if="test/junit-present">
    <checksum file="${junit-platform.jar}" algorithm="SHA-256"
              property="${junit-platform.sha256}" verifyproperty="test/junit-valid" />
    <condition property="test/has-junit">
      <istrue value="${test/junit-valid}" />
    </condition>
  </target>

  <target name="test-deps" depends="test-verify" unless="test/has-junit">
    <delete file="${junit-platform.jar}" />
    <get src="https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-console-standalone/${junit-platform.version}/junit-platform-console-standalone-${junit-platform.version}.jar"
         dest="${junit-platform.jar}" maxtime="60" retries="3" />
    <checksum file="${junit-platform.jar}" algorithm="SHA-256"
              property="${junit-platform.sha256}" verifyproperty="test/junit-download-valid" />
    <fail message="Downloaded JUnit jar has an unexpected checksum">
      <condition>
        <not><istrue value="${test/junit-download-valid}" /></not>
      </condition>
    </fail>
  </target>

  <target name="test-compile" depends="hafen-client, test-deps">
    <delete dir="build/test-classes" />
    <mkdir dir="build/test-classes" />
    <javac srcdir="test" destdir="build/test-classes" debug="on"
           source="1.8" target="1.8" includeantruntime="no" encoding="UTF-8">
      <classpath>
        <pathelement path="build/classes" />
        <path refid="client.classpath" />
        <pathelement location="${junit-platform.jar}" />
      </classpath>
      <compilerarg value="-Xlint:-options" />
    </javac>
  </target>

  <target name="test" depends="test-compile" description="Run local tests">
    <java classname="org.junit.platform.console.ConsoleLauncher" fork="true" failonerror="true">
      <classpath>
        <pathelement path="build/classes" />
        <pathelement path="build/test-classes" />
        <path refid="client.classpath" />
        <pathelement location="${junit-platform.jar}" />
      </classpath>
      <arg value="execute" />
      <arg value="--disable-banner" />
      <arg value="--scan-class-path=build/test-classes" />
      <arg value="--fail-if-no-tests" />
      <arg value="--details=summary" />
    </java>
  </target>

  <target name="clean">
    <delete dir="build" />
    <delete dir="lib/ext" />
    <delete dir="bin" />
  </target>

  <target name="resources">
    <exec executable="java" failifexecutionfails="false">
      <arg line="-jar etc/LayerUtil.jar -re resources/src resources/compiled/res" />
    </exec>
    <jar destfile="build/nurgling-res.jar" update="true">
      <fileset dir="resources/compiled" />
    </jar>
    <copy todir="bin/" file="build/nurgling-res.jar" />
    <copy todir="bin/" file="etc/json-java.jar" />
    <copy todir="bin/" file="etc/postgresql-42.7.5.jar" />
    <copy todir="bin/" file="etc/sqlite-jdbc-3.49.1.0.jar" />
  </target>

  <!-- JOGL 2.5.0 for macOS only. The common JOGL natives are x86_64-only and fail on Apple
       Silicon; these carry arm64 too. They go to release/platform/macos/, which the updater
       installs on Macs in place of the common jars (Windows and Linux keep theirs). -->
  <target name="extlib/jogl-macos" depends="extlib-env">
    <property name="jogl-macos.url" value="https://jogamp.org/deployment/v2.5.0/jar" />
    <mkdir dir="lib/ext/jogl-macos" />
    <get dest="lib/ext/jogl-macos/" skipexisting="true">
      <url url="${jogl-macos.url}/jogl-all.jar" />
      <url url="${jogl-macos.url}/gluegen-rt.jar" />
      <url url="${jogl-macos.url}/jogl-all-natives-macosx-universal.jar" />
      <url url="${jogl-macos.url}/gluegen-rt-natives-macosx-universal.jar" />
    </get>
    <checksum file="lib/ext/jogl-macos/jogl-all.jar" algorithm="SHA-256" property="245717cceabca264a210a899f8839d47bd127f50f80892ead2277dd89cbcd301" verifyproperty="jogl-macos.ok.jogl" />
    <checksum file="lib/ext/jogl-macos/gluegen-rt.jar" algorithm="SHA-256" property="3620c18536a8671fcb1c595d7448e9d31226b824117af6a4c6d45c657f4dabe3" verifyproperty="jogl-macos.ok.gluegen" />
    <checksum file="lib/ext/jogl-macos/jogl-all-natives-macosx-universal.jar" algorithm="SHA-256" property="032e56167443a80f9f4477fbeef255e59988c6cd5237a151b948bde4bcb7c80c" verifyproperty="jogl-macos.ok.joglnat" />
    <checksum file="lib/ext/jogl-macos/gluegen-rt-natives-macosx-universal.jar" algorithm="SHA-256" property="3dbd5d054f108c3f8c0c07281e6e3494b85b89b0d8b3f0fbef4bf6c41ca254ec" verifyproperty="jogl-macos.ok.gluegennat" />
    <fail message="JOGL 2.5.0 macOS jars failed their checksums; delete lib/ext/jogl-macos and retry">
      <condition>
        <not><and>
          <istrue value="${jogl-macos.ok.jogl}" />
          <istrue value="${jogl-macos.ok.gluegen}" />
          <istrue value="${jogl-macos.ok.joglnat}" />
          <istrue value="${jogl-macos.ok.gluegennat}" />
        </and></not>
      </condition>
    </fail>
  </target>

  <target name="pre-release" depends="build-env, jar, extlib/jogl, extlib/jogl-macos, extlib/lwjgl-vk, res-jar">
    <copy todir="release/platform/macos">
      <fileset dir="lib/ext/jogl-macos" includes="*.jar" />
    </copy>
    <copy todir="release" failonerror="false" quiet="true">
      <file name="lib/ext/builtin-res.jar" />
      <file name="lib/ext/hafen-res.jar" />
      <file name="etc/json-java.jar" />
      <file name="etc/postgresql-42.7.5.jar" />
      <file name="etc/sqlite-jdbc-3.49.1.0.jar" />
    </copy>
    <copy todir="release">
      <fileset dir="lib/ext/jogl">
        <include name="*.jar" />
      </fileset>
      <fileset dir="lib/ext/lwjgl">
        <include name="*.jar" />
      </fileset>
      <fileset dir="lib/ext/lwjgl-vk">
        <include name="*.jar" />
      </fileset>
    </copy>
    <copy file="etc/ansgar-config.properties" tofile="release/haven-config.properties" failonerror="false" quiet="true" />
    <!-- Linux: JOGL crashes in Mesa's GLX, so every launcher (updater, HnH Scheduler, scripts)
         must pick the LWJGL toolkit. hafen reads haven-config.properties next to hafen.jar,
         and the updater installs this variant on Linux only. -->
    <concat destfile="release/platform/linux/haven-config.properties">
      <filelist dir="etc" files="ansgar-config.properties" />
      <string>${line.separator}haven.toolkit=lwjgl${line.separator}</string>
    </concat>
    <copy todir="release/" file="build/nurgling-res.jar" />
    <copy todir="release/" file="build/hafen.jar" />
    <copy todir="release/" file="etc/run.bat" />
    <copy todir="release/" file="etc/run8.bat" />
  </target>

  <target name="steam-release" depends="build-env, jar, extlib/jogl, extlib/lwjgl-vk">
    <copy todir="steam" failonerror="false" quiet="true">
      <file name="lib/ext/builtin-res.jar" />
      <file name="lib/ext/hafen-res.jar" />
      <file name="etc/json-java.jar" />
      <file name="etc/postgresql-42.7.5.jar"  />
      <file name="etc/sqlite-jdbc-3.49.1.0.jar"  />
      <file name="etc/icon.png" />
    </copy>
    <copy todir="steam">
      <fileset dir="lib/ext/jogl">
        <include name="*.jar" />
      </fileset>
      <fileset dir="lib/ext/lwjgl">
        <include name="*.jar" />
      </fileset>
      <fileset dir="lib/ext/lwjgl-vk">
        <include name="*.jar" />
      </fileset>
    </copy>
    <copy file="etc/workshop-client.properties" tofile="steam/workshop-client.properties" failonerror="false" quiet="true" />
    <copy todir="steam/" file="build/nurgling-res.jar" />
    <copy todir="steam/" file="build/hafen.jar" />
  </target>

  <!-- major.minor; CI appends the build number and the updater's publish step writes ver and manifest.json -->
  <property name="version.num" value="2.103"/>
  <target name="release" depends="pre-release" />
</project>
